name: Acceptance tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update apt repositories
      run: sudo apt -y update
    - name: Install dependencies
      run: sudo apt -y install libtool-bin postgresql
    - name: Start PostgreSQL server
      run: sudo systemctl start postgresql.service
    - name: Create PostgreSQL user
      run: sudo -u postgres createuser --superuser `whoami`
    - name: Bootstrap project
      run: ./bootstrap.sh
    - name: Configure project
      run: >
        ./configure
        --enable-debug
        --with-test-binary
        --with-csv-module
        --with-psql-module
    - name: Compile project
      run: make
    - name: Run acceptance tests
      run: cd tests && python3 acceptance.py
